config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '/', path_names: { sign_in: 'login', sign_out: 'logout' },
             only: [:sessions]

  namespace :registrations do
    resources :admins, only: [:create] do
      get 'sign_up' => 'admins#new', on: :collection
    end

    resources :sellers, only: [:create] do
      get 'sign_up' => 'sellers#new', on: :collection
    end

    resources :guests, only: [:create] do
      get 'sign_up' => 'guests#new', on: :collection
    end
  end

  resources :products do
    post 'buy', on: :member
  end

  root 'products#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    case
    when user.admin?
      can [:read, :update, :destroy, :make_pro, :see_shop], Product
    when user.seller?
      can [:create, :read, :see_shop], Product
      can [:update, :destroy], Product, user_id: user.id
    when user.guest?
      can :read, Product
      can :buy, Product do |product|
        BuyingProcess::Requirements.product_can_be_bought?(product)
      end
    else
      can :read, Product, pro: false
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
class Admin < User
  def admin?
    true
  end

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/guest.rb
class Guest < User
  def guest?
    true
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  mount_uploader :image, SimpleImageUploader
  belongs_to :user

  delegate :shop_name, to: :user, allow_nil: true
end

app/models/seller.rb
class Seller < User
  has_many :products, dependent: :destroy

  def seller?
    true
  end

  def full_name
    self.shop_name
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, password_length: 6..128

  mount_uploader :avatar_image, SimpleImageUploader
  mount_uploader :passport_image, SimpleImageUploader

  def admin?
    false
  end

  def seller?
    false
  end

  def guest?
    false
  end

  def full_name
    email
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    begin
      redirect_to :back, alert: exception.message
    rescue
      redirect_to :root, alert: exception.message
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # before_action :set_product, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /products
  # GET /products.json
  def index
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product.user = current_user
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def buy
    result = BuyingProcess::Manager.buy(customer: current_user, product: @product)
    if result.success?
      redirect_to @product, notice: 'You successfully bought this product!'
    else
      redirect_to @product, flash: { alert: 'Failed to buy this product!', error: result.errors.join('; ') }
    end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image, :pro)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} alert-dismissible", role: 'alert') do
               concat(content_tag(:button, class: 'close', data: { dismiss: 'alert' }) do
                        concat content_tag(:span, '&times;'.html_safe, 'aria-hidden' => true)
                        concat content_tag(:span, 'Close', class: 'sr-only')
                      end)
               concat message
             end)
    end
    nil
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Training project', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li <%= params[:controller] == 'products' ? 'class=active' : '' %>><%= link_to 'Products', products_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/user_links' %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_user_links.html.erb
<% if current_user %>
  <li class="nav-bar-user"><%= "Welcome back, #{current_user.full_name} (#{current_user.class.name.capitalize})" %></li>
  <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
<% else %>
  <li><%= link_to 'Log in', new_user_session_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Training</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navigation' %>

<div class="container-fluid">
  <%= yield %>
</div>

</body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Training</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body class="gray-bg">
<div class="middle-box text-center loginscreen  animated fadeInDown">
  <%= flash_messages %>
  <%= yield %>
</div>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for @product, :html => { :class => "form-horizontal product", multipart: true } do |f| %>

  <% if @product.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@product.errors.count, "error") %> prohibited this product from being
          saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
          <% @product.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@product[:name]) %>
  </div>
  <% if can? :make_pro, Product %>
    <div class="control-group text-left">
      <%= f.check_box :pro %>
      <%= f.label :pro %>
    </div>
  <% end %>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%= error_span(@product[:description]) %>
  </div>
  <div class="control-group">
    <%= f.label :image, :class => 'control-label' %>
    <%= image_tag(@product.image_url) if @product.image? %>
    <div class="controls">
      <%= f.file_field :image, :class => 'form-control' %>
    </div>
    <%= error_span(@product[:image]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
              products_path, :class => 'btn btn-default' %>

<% end %>

app/views/products/edit.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/index.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%= t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
  <tr>
    <th><%= model_class.human_attribute_name(:id) %></th>
    <th><%= model_class.human_attribute_name(:name) %></th>
    <th><%= model_class.human_attribute_name(:description) %></th>
    <% if can? :see_shop, Product %>
      <th><%= model_class.human_attribute_name(:shop_name) %></th>
    <% end %>
    <% if can? :make_pro, Product %>
      <th><%= model_class.human_attribute_name(:pro) %></th>
    <% end %>
    <% if can? :update, Product %>
      <th><%= t '.actions', :default => t("helpers.actions") %></th>
    <% end %>
  </tr>
  </thead>
  <tbody>
  <% @products.each do |product| %>
    <tr>
      <td><%= link_to product.id, product_path(product) %></td>
      <td><%= link_to product.name, product_path(product) %></td>
      <td><%= product.description %></td>

      <% if can? :see_shop, Product %>
        <td><%= product.shop_name %></td>
      <% end %>
      <% if can? :make_pro, Product %>
        <td><i class="<%= product.pro? ? 'fa fa-check-circle-o' : '' %>"></i></td>
      <% end %>
      <td>
        <% if can? :update, product %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_product_path(product), :class => 'btn btn-default btn-xs',
                      method:                            :get %>
        <% end %>
        <% if can? :destroy, product %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      product_path(product),
                      :method => :delete,
                      :data   => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class  => 'btn btn-xs btn-danger' %>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<% if can? :create, Product %>
  <%= button_to t('.new', :default => t("helpers.links.new")),
                new_product_path,
                :class  => 'btn btn-primary',
                method: :get %>
<% end %>

app/views/products/new.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/show.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%= t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @product.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @product.description %></dd>
  <% if can? :see_shop, @product %>
    <dt><strong><%= model_class.human_attribute_name(:shop_name) %>:</strong></dt>
    <dd><%= @product.shop_name %></dd>
  <% end %>
  <%= image_tag(@product.image_url) if @product.image? %>
</dl>

<% if can? :buy, @product %>
  <%= link_to t('products.actions.buy'),
              buy_product_path, :class => 'btn btn-default', method: :post %>
<% end %>

<%= link_to t('.back', :default => t("helpers.links.back")),
            products_path, :class => 'btn btn-default' %>

<% if can? :update, @product %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_product_path(@product), :class => 'btn btn-default' %>
<% end %>

<% if can? :destroy, @product %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              product_path(@product),
              :method => 'delete',
              :data   => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class  => 'btn btn-danger' %>
<% end %>